import "./globals.css";
import type { Metadata } from "next";
import { Playfair_Display, Source_Sans_3 } from "next/font/google";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});

const sourceSans = Source_Sans_3({
  subsets: ["latin"],
  variable: "--font-source-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "HPC LaTeX Editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="fa"
      dir="ltr"
      className={`${playfair.variable} ${sourceSans.variable}`}
    >
      <head>
        <link href="/fonts/vazirmatn.css" rel="stylesheet" />
      </head>
      <body className="font-vazirmatn">{children}</body>
    </html>
  );
}
