import './globals.css';
import type { Metadata } from 'next';
import { Playfair_Display, Source_Sans_3 } from 'next/font/google';
import I18nProvider from './_components/I18nProvider'; // Adjust the path if needed

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
  display: 'swap',
});

const sourceSans = Source_Sans_3({
  subsets: ['latin'],
  variable: '--font-source-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'HPC LaTeX Editor',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale: 'en' | 'fa' = 'fa';
  return (
    <html lang={locale} className={`${playfair.variable} ${sourceSans.variable}`} data-theme="overleafTheme">
      <body className="font-body">
      <I18nProvider locale={locale}>
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}